# Generated by Django 3.2.5 on 2021-08-08 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210807_1604'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UrlData',
        ),
    ]
