# Generated by Django 3.2.5 on 2021-08-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldata',
            name='slug',
            field=models.CharField(max_length=20, unique=True, verbose_name='Короткая ссылка'),
        ),
        migrations.AlterField(
            model_name='urldata',
            name='url',
            field=models.CharField(max_length=255, verbose_name='Длинная ссылка'),
        ),
    ]
